url: https://idhikafoundation.com
author: Idhika Foundation
layout_dir: _layouts
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-sitemap