title: Idhika Foundation | Women & Girl Child Empowerment
description: We are working towards Empowerment of Women and Girl Child and trying to bring change in perspective of women, girls and elderly
url: https://idhikafoundation.com
author: Idhika Foundation
layout_dir: _layouts
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-sitemap